config/routes.rb
Rails.application.routes.draw do

  get 'welcome/home'

  get 'users/new'

  get 'users/create'

  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'

  delete "users/:id" => "users#destroy"

  resources :matches
  root "welcome#home"

  resources :comments
  patch "comments/:id" => "comments#update"
  delete "comments/:id" => "comments#destroy"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :match
end

app/models/match.rb
class Match < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  # Verify that an email exists and that it does not already exist in the db
  validates :email, presence: true, uniqueness: true

  has_and_belongs_to_many :matches
  has_many :comments

  has_attached_file :picture_file_name, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture_file_name, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


   private

     # Make the current_user method available to views, not just controllers!
    helper_method :current_user

  def current_user
    @current_user ||= begin
      User.find(session[:user_id]) if session[:user_id]
    rescue
      session[:user_id] = nil
      nil
    end
  end
    def authorize
      redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:index, :show]
  before_action :only_my_comments, only: [:edit, :update, :destroy]

    def index
    @comments = Comment.all
    end

    def new
    @comment = Comment.new
    end

    def create
    @comment = Comment.new(params.require(:comment).permit(:content, :user_id, :match_id))
    @comment.user = current_user
        if @comment.save
          redirect_to match_path(@comment.match)
       else
          render :new
      end
    end


  def edit
    @comment = Comment.find(params[:id])
  end

  def update
     @comment = Comment.find(params[:id])

        if @comment.update_attributes(params.require(:comment).permit(:content, :user_id, :match_id))
              redirect_to match_path(@comment.match)
        else
               render :edit
       end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to match_path(@comment.match)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :match_id)
    end

    def only_my_comments
      redirect_to match_path(@comment.match), notice: "you can't edit someone elses tweets" if (current_user != @comment.user)
    end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  # before_action :set_match, only: [:show, :edit, :update, :destroy]
  # before_action :authorize, except: [:index, :show]

    def index
    @matches = Match.all

    if current_user.preference == "Women" || current_user.preference == "women"
      @matches = @matches.select { |match| match.gender == "Female"}
    elsif
      current_user.preference == "Men" || current_user.preference == "men"
      @matches = @matches.select { |match| match.gender == "Male"}
    else
      @matches = Match.all
    end

    end

    def show
    @match = Match.find(params[:id])
    end

    def new
    @comment = Comment.new
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to matches_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid login credentials - try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #this syntax helps the sign up page
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed up!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end


  def edit
    @user = User.find(params[:id])
    end

    def update
    @user = User.find(params[:id])

        if @user.update_attributes(params.require(:user).permit(:first_name, :last_name, :email, :gender, :age, :preference, :password_digest))
              redirect_to user_path
        else
               render :edit
       end
  end


  def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to root_path
  end


   private
        def user_params
            params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :picture_file_name, :last_name, :gender, :age, :preference)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    # if @user == true,
    #   render :matches.index
    # else
    #   render :welcome.home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/emoji_helper.rb
module EmojiHelper
  def emojify(content)
    h(content).to_str.gsub(/:([\w+-]+):/) do |match|
      if emoji = Emoji.find_by_alias($1)
        %(<img alt="#$1" src="#{image_path("emoji/#{emoji.image_filename}")}" style="vertical-align:middle" width="20" height="20" />)
      else
        match
      end
    end.html_safe if content.present?
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/edit.html.erb
<div class="webcontainer">

<div class="editcomment">
<h1>Edit</h1>

<%= form_for @comment do |f| %>

    <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
    </div>

    <br>
    <%= f.submit "Submit these changes!" %>

<% end %>
<br>
<%= link_to "Back to Today's Matches!", matches_path %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project2new</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<div class = "webcontainer">
<body class= '<%= controller.controller_path %> <%= controller.action_name %>'>

<!-- below is the basic css downloaded from bootwatch>
 -->

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= link_to 'Logout', session_path('dummy'), method: :delete %></li>
        <% else %>
        <%= link_to 'Login', login_path %>
        <%= link_to 'Sign Up', new_user_path %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<!-- Today's Matches page and syntaxes>
 -->
<h1 class ="h1fantasy">Fantasy Dating <%= emojify(":fire:") %></h1>

<p>
  <% if current_user %>

    Welcome, <%= current_user.first_name %>
      |
    <%= link_to 'Profile', user_path(current_user) %>


  <% else %>
    <%= link_to 'Login', login_path %>
      |
    <%= link_to 'Sign Up', new_user_path %>
  <% end %>

</p>

<%= yield %>

</body>
</html>
</div>

app/views/matches/index.html.erb
<div class = "webcontainer">
<h1 class="h1today">Today's Matches: I Want You So Bad <%= emojify(":smiling_imp:") %></h1>


<ul class="scroll_match">
    <% @matches.each do |match| %>
        <li>
            <strong> <%= match.first_name %> </strong>
            <div class="field">

  </div>

            <img src="<%= match.image %>" width=100px height=100px>
            <%= link_to emojify("Check Me Out :heart:"), match_path(match) %>

        </li>
    <% end %>
</ul>
</div>

app/views/matches/show.html.erb
<div class ="webcontainer">
<h1> <%= @match.first_name %> </h1>

<img src="<%= @match.image %>" width=200px height=200px>
<p>Hi, my name is <%= @match.first_name %> <%= @match.last_name %></p>
<p>I am a <%= @match.gender %></p>
<p>I am <%= @match.age %> years old</p>


<p class = "existing_comment">Existing Comments: </p><br>
<ul class = "comment_class">
<% @match.comments.each do |comment| %>
  <li><%= comment.content %><br>
  From User: <%= comment.user.first_name %> <%= comment.user.last_name %><br>
  <%= link_to "Edit", "/comments/#{comment.id}/edit" %>
  |
  <%= link_to "Delete!", comment, method: :delete, data: { confirm: "Are you sure you want to delete this comment?"} %>
  </li>
<% end %>
</ul>

<!-- line 23 is to fix the "new" comment that we didnt build. before it was
 form_for @comment do |f|  -->
<%= form_for @match.comments.build(:user_id => current_user.id) do |f| %>

    <%= f.hidden_field :match_id %>
    <%= f.hidden_field :user_id %>

    <div>

        <%= f.label :content %>
        <%= f.text_field :content %>
    </div>



    <%= f.submit "Holla at me!" %> <%= emojify(":kissing_heart:") %>

<% end %>


<%= link_to "Back to Today's Matches!", matches_path %>
</div>

app/views/users/edit.html.erb
<div class="webcontainer">

<div class="edituser">
<h1>Edit</h1>

<%= form_for @user do |f| %>

    <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
    </div>

     <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
     </div>

    <div class="field">
    <%= f.label :gender %><br>
    <%= f.select :gender, %w{Male Female}, :prompt => 'Select', required: true, placeholder: 'Gender', class: 'form-control' %>
    </div>


    <!-- just for documentation
    drop down menu with embedded ruby-->
    <div class="field">
    <%= f.label :preference %><br>
    <%= f.select :preference, %w{Women Men Both}, :prompt => 'Select', required: true, placeholder: 'Gender', class: 'form-control' %>
    </div>


    <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
    </div>
  <br>
    <%= f.submit "Submit these changes!" %>

<% end %>
<br>
<%= link_to "Back to Today's Matches!", matches_path %>
</div>
</div>

app/views/users/new.html.erb
<div class="webcontainer">

<div class="signup_container">
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :gender %><br>
    <%= f.select :gender, %w{Male Female}, :prompt => 'Select', required: true, placeholder: 'Gender', class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :preference %><br>
    <%= f.select :preference, %w{Women Men Both}, :prompt => 'Select', required: true, placeholder: 'Gender', class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>
  </div>

  <div class="field">
  <%= f.file_field :picture_file_name %>
  </div>

  <div class="actions"><%= f.submit %></div>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="webcontainer">

<div class="userprofile">
<h1> <%= @user.first_name %> </h1>


<% if @user.picture_file_name.present? %>
<%= image_tag @user.picture_file_name.url(:medium) %>
<% end %>


<p>Hi my name is <%= @user.first_name %> <%= @user.last_name %></p>
<p>I am a <%= @user.gender %></p>
<p>I am interested in <%= @user.preference %></p>
<p>I am <%= @user.age %> years old</p>

<%= link_to "Edit", edit_user_path(@user) %>

|

<%= link_to "Delete Account", user_path, method: :delete, data: { confirm: "Are you sure you want to delete this Account?"} %>

|

<%= link_to "Today's Matches", matches_path %>
</div>
</div>